{"name": "test_steps_demo[unittest]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './result/photo/a.png'", "trace": "test_ztc = 'unittest'\n\n    @allure.testcase(\"http://www.github.com\")\n    @allure.feature(\"百度搜索\")\n    @pytest.mark.parametrize('test_ztc',['allure','pytest','unittest'])\n    # @pytest.mark.parametrize('test_ztc',yaml.safe_load(\\open(\"data/data.yml\")))\n    def test_steps_demo(test_ztc):\n        with allure.step(\"打开百度网页\"):\n            driver = webdriver.Chrome(\"D:\\TestTools\\webdriver\\chromedriver.exe\")\n            driver.get(\"http://www.baidu.com\")\n            driver.maximize_window()\n    \n        with allure.step(f\"输入搜索词：{test_ztc}\"):\n            driver.find_element_by_id(\"kw\").send_keys(test_ztc)\n            time.sleep(2)\n            driver.find_element_by_id(\"su\").click()\n            time.sleep(2)\n    \n        with allure.step(\"保存图片\"):\n            driver.save_screenshot(\"./result/photo/a.png\")\n>           allure.attach.file(\"./result/photo/a.png\",attachment_type=allure.attachment_type.PNG)\n\ntest_baidudemo.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n..\\testpro\\venv_new\\lib\\site-packages\\allure_pytest\\listener.py:224: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n..\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\reporter.py:113: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n..\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py:432: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = './result/photo/a.png', dst = 'E:\\\\zhangtiechuan\\\\PycharmProjects\\\\allure_project\\\\result\\\\baidu\\\\986b61ad-990e-4bea-ba0f-becbb9684376-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\nE           FileNotFoundError: [Errno 2] No such file or directory: './result/photo/a.png'\n\nC:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py:261: FileNotFoundError"}, "steps": [{"name": "打开百度网页", "status": "passed", "start": 1612776140623, "stop": 1612776152578}, {"name": "输入搜索词：unittest", "status": "passed", "start": 1612776152578, "stop": 1612776156995}, {"name": "保存图片", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './result/photo/a.png'\n", "trace": "  File \"E:\\zhangtiechuan\\PycharmProjects\\allure_project\\test_baidudemo.py\", line 25, in test_steps_demo\n    allure.attach.file(\"./result/photo/a.png\",attachment_type=allure.attachment_type.PNG)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\_allure.py\", line 182, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\allure_pytest\\listener.py\", line 224, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\reporter.py\", line 113, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\zhangtiechuan\\pycharmprojects\\testpro\\venv_new\\lib\\site-packages\\allure_commons\\logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py\", line 432, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shutil.py\", line 261, in copyfile\n    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\n"}, "attachments": [{"source": "986b61ad-990e-4bea-ba0f-becbb9684376-attachment.png", "type": "image/png"}], "start": 1612776156995, "stop": 1612776157319}], "parameters": [{"name": "test_ztc", "value": "'unittest'"}], "start": 1612776140622, "stop": 1612776157321, "uuid": "00118a20-68e1-4cef-a704-ebccbf1d4134", "historyId": "9d3532b766754098dc367a1f5ff7e69c", "testCaseId": "c1bd71ed6b29aa553aa5af4cbca54344", "fullName": "test_baidudemo#test_steps_demo", "labels": [{"name": "feature", "value": "百度搜索"}, {"name": "suite", "value": "test_baidudemo"}, {"name": "host", "value": "SC-202009151434"}, {"name": "thread", "value": "56576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_baidudemo"}], "links": [{"type": "test_case", "url": "http://www.github.com", "name": "http://www.github.com"}]}